baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "re-terminal"

[params]

  contentTypeName = "posts"

  themeColor = "green"

  showMenuItems = 5

  showLanguageSelector = true

  fullWidthTheme = false

  centerTheme = false

  autoCover = true

  showLastUpdated = true

  Toc = true

  readingTime = true

[languages]
  [languages.en.params]
    languageName = "English"
    title = "Samson Danziger"
    subtitle = "A simple, personal website."
    owner = "samson@danziger.uk"
    keywords = ""
    copyright = "2025"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "Samson Danziger"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
      #[[languages.en.menu.main]]
      #  identifier = "showcase"
      #  name = "Showcase"
      #  url = "/showcase"
